import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Providers from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbar/>
        <main className="bg-purple-100 p-10 mx-auto w-full min-h-[100vh]">
          <Providers>
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
